service: chatgpt-aws-lambda

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  profile: ${env:PROFILE} # Read env variable
  memorySize: 128

functions:
  main:
    handler: main

plugins:
  - serverless-offline
