service: chatgpt-aws-lambda

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  profile: ${env:PROFILE} # Read env variable
  memorySize: 128
  timeout: 15
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

package:
  individually: true

functions:
  app:
    package:
      patterns:
        - '!requirements.txt'
        - '!package.json'
        - '!package-lock.json'
        - '!venv/**'
        - '!node_modules/**'
        - '!LICENSE'
        - '!README.md'
        - '!.idea/**'
    handler: main.handler
    layers:
      - Ref:
          - PythonRequirementsLambdaLayer
    events:
      - httpApi:
          method: get
          path: /
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true